// Code generated by protoc-gen-go.
// source: msg.proto
// DO NOT EDIT!

/*
Package msg is a generated protocol buffer package.

It is generated from these files:
	msg.proto

It has these top-level messages:
	PBDReqDataMsg
	PBSResDataMsg
	DReqKeyGenMsg
	DResKeyGenMsg
	PBDDlsReqMsg
	PBDDlsResMsg
	LmtDDlsReqMsg
	LmtDDlsResMsg
	PBDReqMultiDataMsg
	PBSResMultiDataMsg
	PBDemOrderManualMsg
	PBDlsOrderManualMsg
*/
package msg_dem

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 需方请求供方PB
type PBDReqDataMsg struct {
	TranInfo         *PBDReqDataMsg_TranInfo       `protobuf:"bytes,1,req,name=tranInfo" json:"tranInfo,omitempty"`
	CertInfo         *PBDReqDataMsg_CertInfo       `protobuf:"bytes,2,req,name=certInfo" json:"certInfo,omitempty"`
	SignInfo         []*PBDReqDataMsg_SignStepInfo `protobuf:"bytes,3,rep,name=signInfo" json:"signInfo,omitempty"`
	TaskType         []*PBDReqDataMsg_TaskType     `protobuf:"bytes,4,rep,name=taskType" json:"taskType,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *PBDReqDataMsg) Reset()                    { *m = PBDReqDataMsg{} }
func (m *PBDReqDataMsg) String() string            { return proto.CompactTextString(m) }
func (*PBDReqDataMsg) ProtoMessage()               {}
func (*PBDReqDataMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// Crp需方请求供方PB
type CrpPBDReqDataMsg struct {
	TranInfo *CrpPBDReqDataMsg_TranInfo `protobuf:"bytes,1,req,name=tranInfo" json:"tranInfo,omitempty"`
	//	CertInfo         *PBDReqDataMsg_CertInfo       `protobuf:"bytes,2,req,name=certInfo" json:"certInfo,omitempty"`
	//	SignInfo         []*PBDReqDataMsg_SignStepInfo `protobuf:"bytes,3,rep,name=signInfo" json:"signInfo,omitempty"`
	//	TaskType         []*PBDReqDataMsg_TaskType     `protobuf:"bytes,4,rep,name=taskType" json:"taskType,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CrpPBDReqDataMsg) Reset()                    { *m = CrpPBDReqDataMsg{} }
func (m *CrpPBDReqDataMsg) String() string            { return proto.CompactTextString(m) }
func (*CrpPBDReqDataMsg) ProtoMessage()               {}
func (*CrpPBDReqDataMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PBDReqDataMsg) GetTranInfo() *PBDReqDataMsg_TranInfo {
	if m != nil {
		return m.TranInfo
	}
	return nil
}

func (m *PBDReqDataMsg) GetCertInfo() *PBDReqDataMsg_CertInfo {
	if m != nil {
		return m.CertInfo
	}
	return nil
}

func (m *PBDReqDataMsg) GetSignInfo() []*PBDReqDataMsg_SignStepInfo {
	if m != nil {
		return m.SignInfo
	}
	return nil
}

func (m *PBDReqDataMsg) GetTaskType() []*PBDReqDataMsg_TaskType {
	if m != nil {
		return m.TaskType
	}
	return nil
}

type CrpPBDReqDataMsg_TranInfo struct {
	//	RequestId     *string `protobuf:"bytes,1,req,name=requestId" json:"requestId,omitempty"`
	//	UserId        *string `protobuf:"bytes,2,req,name=userId" json:"userId,omitempty"`
	//	TaskId        *string `protobuf:"bytes,3,req,name=taskId" json:"taskId,omitempty"`
	//	IdType        *string `protobuf:"bytes,4,req,name=idType" json:"idType,omitempty"`
	BusiInfo *map[string]string `protobuf:"bytes,1,req,name=busiInfo" json:"busiInfo,omitempty"`
	//	DataRange     *string `protobuf:"bytes,6,req,name=data_range" json:"data_range,omitempty"`
	//	ServiceId     *string `protobuf:"bytes,7,req,name=serviceId" json:"serviceId,omitempty"`
	PubReqInfo       *map[string]string `protobuf:"bytes,2,req,name=pubReqInfo" json:"pubReqInfo,omitempty"`
	TranInfo         *map[string]string `protobuf:"bytes,2,req,name=tranInfo" json:"tranInfo,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *CrpPBDReqDataMsg_TranInfo) Reset()         { *m = CrpPBDReqDataMsg_TranInfo{} }
func (m *CrpPBDReqDataMsg_TranInfo) String() string { return proto.CompactTextString(m) }
func (*CrpPBDReqDataMsg_TranInfo) ProtoMessage()    {}

type PBDReqDataMsg_TranInfo struct {
	RequestId *string `protobuf:"bytes,1,req,name=requestId" json:"requestId,omitempty"`
	UserId    *string `protobuf:"bytes,2,req,name=userId" json:"userId,omitempty"`
	TaskId    *string `protobuf:"bytes,3,req,name=taskId" json:"taskId,omitempty"`
	IdType    *string `protobuf:"bytes,4,req,name=idType" json:"idType,omitempty"`
	//	Etid          *string `protobuf:"bytes,5,req,name=etid" json:"etid,omitempty"
	CommonId         *string `protobuf:"bytes,5,req,name=commonId" json:"commonId,omitempty"`
	DataRange        *string `protobuf:"bytes,6,req,name=data_range" json:"data_range,omitempty"`
	ServiceId        *string `protobuf:"bytes,7,req,name=serviceId" json:"serviceId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PBDReqDataMsg_TranInfo) Reset()                    { *m = PBDReqDataMsg_TranInfo{} }
func (m *PBDReqDataMsg_TranInfo) String() string            { return proto.CompactTextString(m) }
func (*PBDReqDataMsg_TranInfo) ProtoMessage()               {}
func (*PBDReqDataMsg_TranInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *PBDReqDataMsg_TranInfo) GetRequestId() string {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return ""
}

func (m *PBDReqDataMsg_TranInfo) GetUserId() string {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return ""
}

func (m *PBDReqDataMsg_TranInfo) GetTaskId() string {
	if m != nil && m.TaskId != nil {
		return *m.TaskId
	}
	return ""
}

func (m *PBDReqDataMsg_TranInfo) GetIdType() string {
	if m != nil && m.IdType != nil {
		return *m.IdType
	}
	return ""
}

func (m *PBDReqDataMsg_TranInfo) GetCommonId() string {
	if m != nil && m.CommonId != nil {
		return *m.CommonId
	}
	return ""
}

func (m *PBDReqDataMsg_TranInfo) GetDataRange() string {
	if m != nil && m.DataRange != nil {
		return *m.DataRange
	}
	return ""
}

type PBDReqDataMsg_CertInfo struct {
	TranHash         *string `protobuf:"bytes,1,req,name=tranHash" json:"tranHash,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PBDReqDataMsg_CertInfo) Reset()                    { *m = PBDReqDataMsg_CertInfo{} }
func (m *PBDReqDataMsg_CertInfo) String() string            { return proto.CompactTextString(m) }
func (*PBDReqDataMsg_CertInfo) ProtoMessage()               {}
func (*PBDReqDataMsg_CertInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

func (m *PBDReqDataMsg_CertInfo) GetTranHash() string {
	if m != nil && m.TranHash != nil {
		return *m.TranHash
	}
	return ""
}

type PBDReqDataMsg_SignStepInfo struct {
	Step             *string `protobuf:"bytes,1,req,name=step" json:"step,omitempty"`
	MemId            *string `protobuf:"bytes,2,req,name=memId" json:"memId,omitempty"`
	Status           *string `protobuf:"bytes,3,req,name=status" json:"status,omitempty"`
	SignBlock        *string `protobuf:"bytes,4,req,name=signBlock" json:"signBlock,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PBDReqDataMsg_SignStepInfo) Reset()                    { *m = PBDReqDataMsg_SignStepInfo{} }
func (m *PBDReqDataMsg_SignStepInfo) String() string            { return proto.CompactTextString(m) }
func (*PBDReqDataMsg_SignStepInfo) ProtoMessage()               {}
func (*PBDReqDataMsg_SignStepInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 2} }

func (m *PBDReqDataMsg_SignStepInfo) GetStep() string {
	if m != nil && m.Step != nil {
		return *m.Step
	}
	return ""
}

func (m *PBDReqDataMsg_SignStepInfo) GetMemId() string {
	if m != nil && m.MemId != nil {
		return *m.MemId
	}
	return ""
}

func (m *PBDReqDataMsg_SignStepInfo) GetStatus() string {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return ""
}

func (m *PBDReqDataMsg_SignStepInfo) GetSignBlock() string {
	if m != nil && m.SignBlock != nil {
		return *m.SignBlock
	}
	return ""
}

type PBDReqDataMsg_TaskType struct {
	Taskid           *string `protobuf:"bytes,1,req,name=taskid" json:"taskid,omitempty"`
	KeyQryType       *string `protobuf:"bytes,2,req,name=keyQryType" json:"keyQryType,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PBDReqDataMsg_TaskType) Reset()                    { *m = PBDReqDataMsg_TaskType{} }
func (m *PBDReqDataMsg_TaskType) String() string            { return proto.CompactTextString(m) }
func (*PBDReqDataMsg_TaskType) ProtoMessage()               {}
func (*PBDReqDataMsg_TaskType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 3} }

func (m *PBDReqDataMsg_TaskType) GetTaskid() string {
	if m != nil && m.Taskid != nil {
		return *m.Taskid
	}
	return ""
}

func (m *PBDReqDataMsg_TaskType) GetKeyQryType() string {
	if m != nil && m.KeyQryType != nil {
		return *m.KeyQryType
	}
	return ""
}

// 供方数据返回PB
type PBSResDataMsg struct {
	TranInfo         *PBSResDataMsg_TranInfo       `protobuf:"bytes,1,req,name=tranInfo" json:"tranInfo,omitempty"`
	DigEnv           *PBSResDataMsg_DigEnv         `protobuf:"bytes,2,opt,name=digEnv" json:"digEnv,omitempty"`
	CertInfo         *PBSResDataMsg_CertInfo       `protobuf:"bytes,3,opt,name=certInfo" json:"certInfo,omitempty"`
	SignInfo         []*PBSResDataMsg_SignStepInfo `protobuf:"bytes,4,rep,name=signInfo" json:"signInfo,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *PBSResDataMsg) Reset()                    { *m = PBSResDataMsg{} }
func (m *PBSResDataMsg) String() string            { return proto.CompactTextString(m) }
func (*PBSResDataMsg) ProtoMessage()               {}
func (*PBSResDataMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PBSResDataMsg) GetTranInfo() *PBSResDataMsg_TranInfo {
	if m != nil {
		return m.TranInfo
	}
	return nil
}

func (m *PBSResDataMsg) GetDigEnv() *PBSResDataMsg_DigEnv {
	if m != nil {
		return m.DigEnv
	}
	return nil
}

func (m *PBSResDataMsg) GetCertInfo() *PBSResDataMsg_CertInfo {
	if m != nil {
		return m.CertInfo
	}
	return nil
}

func (m *PBSResDataMsg) GetSignInfo() []*PBSResDataMsg_SignStepInfo {
	if m != nil {
		return m.SignInfo
	}
	return nil
}

type PBSResDataMsg_TranInfo struct {
	ResCode          *string `protobuf:"bytes,1,req,name=resCode" json:"resCode,omitempty"`
	ResMsg           *string `protobuf:"bytes,2,req,name=resMsg" json:"resMsg,omitempty"`
	TimeStamp        *string `protobuf:"bytes,3,req,name=timeStamp" json:"timeStamp,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PBSResDataMsg_TranInfo) Reset()                    { *m = PBSResDataMsg_TranInfo{} }
func (m *PBSResDataMsg_TranInfo) String() string            { return proto.CompactTextString(m) }
func (*PBSResDataMsg_TranInfo) ProtoMessage()               {}
func (*PBSResDataMsg_TranInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *PBSResDataMsg_TranInfo) GetResCode() string {
	if m != nil && m.ResCode != nil {
		return *m.ResCode
	}
	return ""
}

func (m *PBSResDataMsg_TranInfo) GetResMsg() string {
	if m != nil && m.ResMsg != nil {
		return *m.ResMsg
	}
	return ""
}

func (m *PBSResDataMsg_TranInfo) GetTimeStamp() string {
	if m != nil && m.TimeStamp != nil {
		return *m.TimeStamp
	}
	return ""
}

type PBSResDataMsg_DigEnv struct {
	EncPswd          *string `protobuf:"bytes,1,req,name=encPswd" json:"encPswd,omitempty"`
	DataHash         *string `protobuf:"bytes,2,req,name=dataHash" json:"dataHash,omitempty"`
	DataLen          *string `protobuf:"bytes,3,req,name=dataLen" json:"dataLen,omitempty"`
	Data             *string `protobuf:"bytes,4,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PBSResDataMsg_DigEnv) Reset()                    { *m = PBSResDataMsg_DigEnv{} }
func (m *PBSResDataMsg_DigEnv) String() string            { return proto.CompactTextString(m) }
func (*PBSResDataMsg_DigEnv) ProtoMessage()               {}
func (*PBSResDataMsg_DigEnv) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 1} }

func (m *PBSResDataMsg_DigEnv) GetEncPswd() string {
	if m != nil && m.EncPswd != nil {
		return *m.EncPswd
	}
	return ""
}

func (m *PBSResDataMsg_DigEnv) GetDataHash() string {
	if m != nil && m.DataHash != nil {
		return *m.DataHash
	}
	return ""
}

func (m *PBSResDataMsg_DigEnv) GetDataLen() string {
	if m != nil && m.DataLen != nil {
		return *m.DataLen
	}
	return ""
}

func (m *PBSResDataMsg_DigEnv) GetData() string {
	if m != nil && m.Data != nil {
		return *m.Data
	}
	return ""
}

type PBSResDataMsg_CertInfo struct {
	TranHash         *string `protobuf:"bytes,1,req,name=tranHash" json:"tranHash,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PBSResDataMsg_CertInfo) Reset()                    { *m = PBSResDataMsg_CertInfo{} }
func (m *PBSResDataMsg_CertInfo) String() string            { return proto.CompactTextString(m) }
func (*PBSResDataMsg_CertInfo) ProtoMessage()               {}
func (*PBSResDataMsg_CertInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 2} }

func (m *PBSResDataMsg_CertInfo) GetTranHash() string {
	if m != nil && m.TranHash != nil {
		return *m.TranHash
	}
	return ""
}

type PBSResDataMsg_SignStepInfo struct {
	Step             *string `protobuf:"bytes,1,req,name=step" json:"step,omitempty"`
	MemId            *string `protobuf:"bytes,2,req,name=memId" json:"memId,omitempty"`
	Status           *string `protobuf:"bytes,3,req,name=status" json:"status,omitempty"`
	SignBlock        *string `protobuf:"bytes,4,req,name=signBlock" json:"signBlock,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PBSResDataMsg_SignStepInfo) Reset()                    { *m = PBSResDataMsg_SignStepInfo{} }
func (m *PBSResDataMsg_SignStepInfo) String() string            { return proto.CompactTextString(m) }
func (*PBSResDataMsg_SignStepInfo) ProtoMessage()               {}
func (*PBSResDataMsg_SignStepInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 3} }

func (m *PBSResDataMsg_SignStepInfo) GetStep() string {
	if m != nil && m.Step != nil {
		return *m.Step
	}
	return ""
}

func (m *PBSResDataMsg_SignStepInfo) GetMemId() string {
	if m != nil && m.MemId != nil {
		return *m.MemId
	}
	return ""
}

func (m *PBSResDataMsg_SignStepInfo) GetStatus() string {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return ""
}

func (m *PBSResDataMsg_SignStepInfo) GetSignBlock() string {
	if m != nil && m.SignBlock != nil {
		return *m.SignBlock
	}
	return ""
}

type DReqKeyGenMsg struct {
	MemId            *string `protobuf:"bytes,1,req,name=memId" json:"memId,omitempty"`
	UserPswd         *string `protobuf:"bytes,2,opt,name=userPswd" json:"userPswd,omitempty"`
	KeySeed          *string `protobuf:"bytes,3,req,name=keySeed" json:"keySeed,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DReqKeyGenMsg) Reset()                    { *m = DReqKeyGenMsg{} }
func (m *DReqKeyGenMsg) String() string            { return proto.CompactTextString(m) }
func (*DReqKeyGenMsg) ProtoMessage()               {}
func (*DReqKeyGenMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DReqKeyGenMsg) GetMemId() string {
	if m != nil && m.MemId != nil {
		return *m.MemId
	}
	return ""
}

func (m *DReqKeyGenMsg) GetUserPswd() string {
	if m != nil && m.UserPswd != nil {
		return *m.UserPswd
	}
	return ""
}

func (m *DReqKeyGenMsg) GetKeySeed() string {
	if m != nil && m.KeySeed != nil {
		return *m.KeySeed
	}
	return ""
}

type DResKeyGenMsg struct {
	Status           *string `protobuf:"bytes,1,req,name=status" json:"status,omitempty"`
	ErrNO            *string `protobuf:"bytes,2,req,name=errNO" json:"errNO,omitempty"`
	ErrMsg           *string `protobuf:"bytes,3,req,name=errMsg" json:"errMsg,omitempty"`
	PubKey           *string `protobuf:"bytes,4,req,name=pub_key" json:"pub_key,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *DResKeyGenMsg) Reset()                    { *m = DResKeyGenMsg{} }
func (m *DResKeyGenMsg) String() string            { return proto.CompactTextString(m) }
func (*DResKeyGenMsg) ProtoMessage()               {}
func (*DResKeyGenMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DResKeyGenMsg) GetStatus() string {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return ""
}

func (m *DResKeyGenMsg) GetErrNO() string {
	if m != nil && m.ErrNO != nil {
		return *m.ErrNO
	}
	return ""
}

func (m *DResKeyGenMsg) GetErrMsg() string {
	if m != nil && m.ErrMsg != nil {
		return *m.ErrMsg
	}
	return ""
}

func (m *DResKeyGenMsg) GetPubKey() string {
	if m != nil && m.PubKey != nil {
		return *m.PubKey
	}
	return ""
}

// 需方向DLS发送PB
type PBDDlsReqMsg struct {
	MemId            *string `protobuf:"bytes,1,req,name=memId" json:"memId,omitempty"`
	UserPswd         *string `protobuf:"bytes,2,req,name=userPswd" json:"userPswd,omitempty"`
	Token            *string `protobuf:"bytes,3,req,name=token" json:"token,omitempty"`
	Role             *string `protobuf:"bytes,4,req,name=role" json:"role,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PBDDlsReqMsg) Reset()                    { *m = PBDDlsReqMsg{} }
func (m *PBDDlsReqMsg) String() string            { return proto.CompactTextString(m) }
func (*PBDDlsReqMsg) ProtoMessage()               {}
func (*PBDDlsReqMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PBDDlsReqMsg) GetMemId() string {
	if m != nil && m.MemId != nil {
		return *m.MemId
	}
	return ""
}

func (m *PBDDlsReqMsg) GetUserPswd() string {
	if m != nil && m.UserPswd != nil {
		return *m.UserPswd
	}
	return ""
}

func (m *PBDDlsReqMsg) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *PBDDlsReqMsg) GetRole() string {
	if m != nil && m.Role != nil {
		return *m.Role
	}
	return ""
}

// DLS向需方返回PB
type PBDDlsResMsg struct {
	Status           *string `protobuf:"bytes,1,req,name=status" json:"status,omitempty"`
	ErrNo            *string `protobuf:"bytes,2,req,name=errNo" json:"errNo,omitempty"`
	ErrMsg           *string `protobuf:"bytes,3,req,name=errMsg" json:"errMsg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PBDDlsResMsg) Reset()                    { *m = PBDDlsResMsg{} }
func (m *PBDDlsResMsg) String() string            { return proto.CompactTextString(m) }
func (*PBDDlsResMsg) ProtoMessage()               {}
func (*PBDDlsResMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PBDDlsResMsg) GetStatus() string {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return ""
}

func (m *PBDDlsResMsg) GetErrNo() string {
	if m != nil && m.ErrNo != nil {
		return *m.ErrNo
	}
	return ""
}

func (m *PBDDlsResMsg) GetErrMsg() string {
	if m != nil && m.ErrMsg != nil {
		return *m.ErrMsg
	}
	return ""
}

// 需方向DLS发送额度信息
type LmtDDlsReqMsg struct {
	MemId            *string `protobuf:"bytes,1,req,name=memId" json:"memId,omitempty"`
	UsedBal          *string `protobuf:"bytes,2,req,name=usedBal" json:"usedBal,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LmtDDlsReqMsg) Reset()                    { *m = LmtDDlsReqMsg{} }
func (m *LmtDDlsReqMsg) String() string            { return proto.CompactTextString(m) }
func (*LmtDDlsReqMsg) ProtoMessage()               {}
func (*LmtDDlsReqMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *LmtDDlsReqMsg) GetMemId() string {
	if m != nil && m.MemId != nil {
		return *m.MemId
	}
	return ""
}

func (m *LmtDDlsReqMsg) GetUsedBal() string {
	if m != nil && m.UsedBal != nil {
		return *m.UsedBal
	}
	return ""
}

// DLS向需方返回额度信息
type LmtDDlsResMsg struct {
	Status           *string `protobuf:"bytes,1,req,name=status" json:"status,omitempty"`
	ErrNo            *string `protobuf:"bytes,2,req,name=errNo" json:"errNo,omitempty"`
	ErrMsg           *string `protobuf:"bytes,3,req,name=errMsg" json:"errMsg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LmtDDlsResMsg) Reset()                    { *m = LmtDDlsResMsg{} }
func (m *LmtDDlsResMsg) String() string            { return proto.CompactTextString(m) }
func (*LmtDDlsResMsg) ProtoMessage()               {}
func (*LmtDDlsResMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *LmtDDlsResMsg) GetStatus() string {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return ""
}

func (m *LmtDDlsResMsg) GetErrNo() string {
	if m != nil && m.ErrNo != nil {
		return *m.ErrNo
	}
	return ""
}

func (m *LmtDDlsResMsg) GetErrMsg() string {
	if m != nil && m.ErrMsg != nil {
		return *m.ErrMsg
	}
	return ""
}

// 需方请求供方多页查询PB
type PBDReqMultiDataMsg struct {
	TranInfo         *PBDReqMultiDataMsg_TranInfo       `protobuf:"bytes,1,req,name=tranInfo" json:"tranInfo,omitempty"`
	CondInfo         *PBDReqMultiDataMsg_CondInfo       `protobuf:"bytes,2,req,name=condInfo" json:"condInfo,omitempty"`
	PageCtrl         *PBDReqMultiDataMsg_PageCtrl       `protobuf:"bytes,3,req,name=pageCtrl" json:"pageCtrl,omitempty"`
	CertInfo         *PBDReqMultiDataMsg_CertInfo       `protobuf:"bytes,4,req,name=certInfo" json:"certInfo,omitempty"`
	SignInfo         []*PBDReqMultiDataMsg_SignStepInfo `protobuf:"bytes,5,rep,name=signInfo" json:"signInfo,omitempty"`
	XXX_unrecognized []byte                             `json:"-"`
}

func (m *PBDReqMultiDataMsg) Reset()                    { *m = PBDReqMultiDataMsg{} }
func (m *PBDReqMultiDataMsg) String() string            { return proto.CompactTextString(m) }
func (*PBDReqMultiDataMsg) ProtoMessage()               {}
func (*PBDReqMultiDataMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *PBDReqMultiDataMsg) GetTranInfo() *PBDReqMultiDataMsg_TranInfo {
	if m != nil {
		return m.TranInfo
	}
	return nil
}

func (m *PBDReqMultiDataMsg) GetCondInfo() *PBDReqMultiDataMsg_CondInfo {
	if m != nil {
		return m.CondInfo
	}
	return nil
}

func (m *PBDReqMultiDataMsg) GetPageCtrl() *PBDReqMultiDataMsg_PageCtrl {
	if m != nil {
		return m.PageCtrl
	}
	return nil
}

func (m *PBDReqMultiDataMsg) GetCertInfo() *PBDReqMultiDataMsg_CertInfo {
	if m != nil {
		return m.CertInfo
	}
	return nil
}

func (m *PBDReqMultiDataMsg) GetSignInfo() []*PBDReqMultiDataMsg_SignStepInfo {
	if m != nil {
		return m.SignInfo
	}
	return nil
}

type PBDReqMultiDataMsg_TranInfo struct {
	RequestId        *string `protobuf:"bytes,1,req,name=requestId" json:"requestId,omitempty"`
	UserId           *string `protobuf:"bytes,2,req,name=userId" json:"userId,omitempty"`
	TaskId           *string `protobuf:"bytes,3,req,name=taskId" json:"taskId,omitempty"`
	IdType           *string `protobuf:"bytes,4,req,name=idType" json:"idType,omitempty"`
	CommonId         *string `protobuf:"bytes,5,req,name=commonId" json:"commonId,omitempty"`
	DataRange        *string `protobuf:"bytes,6,req,name=dataRange" json:"dataRange,omitempty"`
	TimeStamp        *string `protobuf:"bytes,7,req,name=timeStamp" json:"timeStamp,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PBDReqMultiDataMsg_TranInfo) Reset()                    { *m = PBDReqMultiDataMsg_TranInfo{} }
func (m *PBDReqMultiDataMsg_TranInfo) String() string            { return proto.CompactTextString(m) }
func (*PBDReqMultiDataMsg_TranInfo) ProtoMessage()               {}
func (*PBDReqMultiDataMsg_TranInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8, 0} }

func (m *PBDReqMultiDataMsg_TranInfo) GetRequestId() string {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return ""
}

func (m *PBDReqMultiDataMsg_TranInfo) GetUserId() string {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return ""
}

func (m *PBDReqMultiDataMsg_TranInfo) GetTaskId() string {
	if m != nil && m.TaskId != nil {
		return *m.TaskId
	}
	return ""
}

func (m *PBDReqMultiDataMsg_TranInfo) GetIdType() string {
	if m != nil && m.IdType != nil {
		return *m.IdType
	}
	return ""
}

func (m *PBDReqMultiDataMsg_TranInfo) GetCommonId() string {
	if m != nil && m.CommonId != nil {
		return *m.CommonId
	}
	return ""
}

func (m *PBDReqMultiDataMsg_TranInfo) GetDataRange() string {
	if m != nil && m.DataRange != nil {
		return *m.DataRange
	}
	return ""
}

func (m *PBDReqMultiDataMsg_TranInfo) GetTimeStamp() string {
	if m != nil && m.TimeStamp != nil {
		return *m.TimeStamp
	}
	return ""
}

type PBDReqMultiDataMsg_CondInfo struct {
	BeginTime        *string `protobuf:"bytes,1,req,name=beginTime" json:"beginTime,omitempty"`
	EndTime          *string `protobuf:"bytes,2,req,name=endTime" json:"endTime,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PBDReqMultiDataMsg_CondInfo) Reset()                    { *m = PBDReqMultiDataMsg_CondInfo{} }
func (m *PBDReqMultiDataMsg_CondInfo) String() string            { return proto.CompactTextString(m) }
func (*PBDReqMultiDataMsg_CondInfo) ProtoMessage()               {}
func (*PBDReqMultiDataMsg_CondInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8, 1} }

func (m *PBDReqMultiDataMsg_CondInfo) GetBeginTime() string {
	if m != nil && m.BeginTime != nil {
		return *m.BeginTime
	}
	return ""
}

func (m *PBDReqMultiDataMsg_CondInfo) GetEndTime() string {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return ""
}

type PBDReqMultiDataMsg_PageCtrl struct {
	ReqPage          *string `protobuf:"bytes,1,req,name=reqPage" json:"reqPage,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PBDReqMultiDataMsg_PageCtrl) Reset()                    { *m = PBDReqMultiDataMsg_PageCtrl{} }
func (m *PBDReqMultiDataMsg_PageCtrl) String() string            { return proto.CompactTextString(m) }
func (*PBDReqMultiDataMsg_PageCtrl) ProtoMessage()               {}
func (*PBDReqMultiDataMsg_PageCtrl) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8, 2} }

func (m *PBDReqMultiDataMsg_PageCtrl) GetReqPage() string {
	if m != nil && m.ReqPage != nil {
		return *m.ReqPage
	}
	return ""
}

type PBDReqMultiDataMsg_CertInfo struct {
	TranHash         *string `protobuf:"bytes,1,req,name=tranHash" json:"tranHash,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PBDReqMultiDataMsg_CertInfo) Reset()                    { *m = PBDReqMultiDataMsg_CertInfo{} }
func (m *PBDReqMultiDataMsg_CertInfo) String() string            { return proto.CompactTextString(m) }
func (*PBDReqMultiDataMsg_CertInfo) ProtoMessage()               {}
func (*PBDReqMultiDataMsg_CertInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8, 3} }

func (m *PBDReqMultiDataMsg_CertInfo) GetTranHash() string {
	if m != nil && m.TranHash != nil {
		return *m.TranHash
	}
	return ""
}

type PBDReqMultiDataMsg_SignStepInfo struct {
	Step             *string `protobuf:"bytes,1,req,name=step" json:"step,omitempty"`
	MemId            *string `protobuf:"bytes,2,req,name=memId" json:"memId,omitempty"`
	Status           *string `protobuf:"bytes,3,req,name=status" json:"status,omitempty"`
	SignBlock        *string `protobuf:"bytes,4,req,name=signBlock" json:"signBlock,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PBDReqMultiDataMsg_SignStepInfo) Reset()         { *m = PBDReqMultiDataMsg_SignStepInfo{} }
func (m *PBDReqMultiDataMsg_SignStepInfo) String() string { return proto.CompactTextString(m) }
func (*PBDReqMultiDataMsg_SignStepInfo) ProtoMessage()    {}
func (*PBDReqMultiDataMsg_SignStepInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{8, 4}
}

func (m *PBDReqMultiDataMsg_SignStepInfo) GetStep() string {
	if m != nil && m.Step != nil {
		return *m.Step
	}
	return ""
}

func (m *PBDReqMultiDataMsg_SignStepInfo) GetMemId() string {
	if m != nil && m.MemId != nil {
		return *m.MemId
	}
	return ""
}

func (m *PBDReqMultiDataMsg_SignStepInfo) GetStatus() string {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return ""
}

func (m *PBDReqMultiDataMsg_SignStepInfo) GetSignBlock() string {
	if m != nil && m.SignBlock != nil {
		return *m.SignBlock
	}
	return ""
}

// 供方多页查询数据返回PB
type PBSResMultiDataMsg struct {
	TranInfo         *PBSResMultiDataMsg_TranInfo       `protobuf:"bytes,1,req,name=tranInfo" json:"tranInfo,omitempty"`
	DigEnv           *PBSResMultiDataMsg_DigEnv         `protobuf:"bytes,2,opt,name=digEnv" json:"digEnv,omitempty"`
	PageCtrl         *PBSResMultiDataMsg_PageCtrl       `protobuf:"bytes,3,opt,name=pageCtrl" json:"pageCtrl,omitempty"`
	CertInfo         *PBSResMultiDataMsg_CertInfo       `protobuf:"bytes,4,opt,name=certInfo" json:"certInfo,omitempty"`
	SignInfo         []*PBSResMultiDataMsg_SignStepInfo `protobuf:"bytes,5,rep,name=signInfo" json:"signInfo,omitempty"`
	XXX_unrecognized []byte                             `json:"-"`
}

func (m *PBSResMultiDataMsg) Reset()                    { *m = PBSResMultiDataMsg{} }
func (m *PBSResMultiDataMsg) String() string            { return proto.CompactTextString(m) }
func (*PBSResMultiDataMsg) ProtoMessage()               {}
func (*PBSResMultiDataMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *PBSResMultiDataMsg) GetTranInfo() *PBSResMultiDataMsg_TranInfo {
	if m != nil {
		return m.TranInfo
	}
	return nil
}

func (m *PBSResMultiDataMsg) GetDigEnv() *PBSResMultiDataMsg_DigEnv {
	if m != nil {
		return m.DigEnv
	}
	return nil
}

func (m *PBSResMultiDataMsg) GetPageCtrl() *PBSResMultiDataMsg_PageCtrl {
	if m != nil {
		return m.PageCtrl
	}
	return nil
}

func (m *PBSResMultiDataMsg) GetCertInfo() *PBSResMultiDataMsg_CertInfo {
	if m != nil {
		return m.CertInfo
	}
	return nil
}

func (m *PBSResMultiDataMsg) GetSignInfo() []*PBSResMultiDataMsg_SignStepInfo {
	if m != nil {
		return m.SignInfo
	}
	return nil
}

type PBSResMultiDataMsg_TranInfo struct {
	BusiSerialNo     *string `protobuf:"bytes,1,req,name=busiSerialNo" json:"busiSerialNo,omitempty"`
	CommomId         *string `protobuf:"bytes,2,req,commonId" json:"commonId,omitempty"`
	ResCode          *string `protobuf:"bytes,3,req,name=resCode" json:"resCode,omitempty"`
	ResMsg           *string `protobuf:"bytes,4,req,name=resMsg" json:"resMsg,omitempty"`
	TimeStamp        *string `protobuf:"bytes,5,req,name=timeStamp" json:"timeStamp,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PBSResMultiDataMsg_TranInfo) Reset()                    { *m = PBSResMultiDataMsg_TranInfo{} }
func (m *PBSResMultiDataMsg_TranInfo) String() string            { return proto.CompactTextString(m) }
func (*PBSResMultiDataMsg_TranInfo) ProtoMessage()               {}
func (*PBSResMultiDataMsg_TranInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9, 0} }

func (m *PBSResMultiDataMsg_TranInfo) GetBusiSerialNo() string {
	if m != nil && m.BusiSerialNo != nil {
		return *m.BusiSerialNo
	}
	return ""
}

func (m *PBSResMultiDataMsg_TranInfo) GetCommonId() string {
	if m != nil && m.CommomId != nil {
		return *m.CommomId
	}
	return ""
}

func (m *PBSResMultiDataMsg_TranInfo) GetResCode() string {
	if m != nil && m.ResCode != nil {
		return *m.ResCode
	}
	return ""
}

func (m *PBSResMultiDataMsg_TranInfo) GetResMsg() string {
	if m != nil && m.ResMsg != nil {
		return *m.ResMsg
	}
	return ""
}

func (m *PBSResMultiDataMsg_TranInfo) GetTimeStamp() string {
	if m != nil && m.TimeStamp != nil {
		return *m.TimeStamp
	}
	return ""
}

type PBSResMultiDataMsg_DigEnv struct {
	EncPswd          *string `protobuf:"bytes,1,req,name=encPswd" json:"encPswd,omitempty"`
	DataHash         *string `protobuf:"bytes,2,req,name=dataHash" json:"dataHash,omitempty"`
	DataLen          *string `protobuf:"bytes,3,req,name=dataLen" json:"dataLen,omitempty"`
	Data             *string `protobuf:"bytes,4,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PBSResMultiDataMsg_DigEnv) Reset()                    { *m = PBSResMultiDataMsg_DigEnv{} }
func (m *PBSResMultiDataMsg_DigEnv) String() string            { return proto.CompactTextString(m) }
func (*PBSResMultiDataMsg_DigEnv) ProtoMessage()               {}
func (*PBSResMultiDataMsg_DigEnv) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9, 1} }

func (m *PBSResMultiDataMsg_DigEnv) GetEncPswd() string {
	if m != nil && m.EncPswd != nil {
		return *m.EncPswd
	}
	return ""
}

func (m *PBSResMultiDataMsg_DigEnv) GetDataHash() string {
	if m != nil && m.DataHash != nil {
		return *m.DataHash
	}
	return ""
}

func (m *PBSResMultiDataMsg_DigEnv) GetDataLen() string {
	if m != nil && m.DataLen != nil {
		return *m.DataLen
	}
	return ""
}

func (m *PBSResMultiDataMsg_DigEnv) GetData() string {
	if m != nil && m.Data != nil {
		return *m.Data
	}
	return ""
}

type PBSResMultiDataMsg_PageCtrl struct {
	TotNum           *string `protobuf:"bytes,1,req,name=totNum" json:"totNum,omitempty"`
	TotPages         *string `protobuf:"bytes,2,req,name=totPages" json:"totPages,omitempty"`
	CurPage          *string `protobuf:"bytes,3,req,name=curPage" json:"curPage,omitempty"`
	CurPageNum       *string `protobuf:"bytes,4,req,name=curPageNum" json:"curPageNum,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PBSResMultiDataMsg_PageCtrl) Reset()                    { *m = PBSResMultiDataMsg_PageCtrl{} }
func (m *PBSResMultiDataMsg_PageCtrl) String() string            { return proto.CompactTextString(m) }
func (*PBSResMultiDataMsg_PageCtrl) ProtoMessage()               {}
func (*PBSResMultiDataMsg_PageCtrl) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9, 2} }

func (m *PBSResMultiDataMsg_PageCtrl) GetTotNum() string {
	if m != nil && m.TotNum != nil {
		return *m.TotNum
	}
	return ""
}

func (m *PBSResMultiDataMsg_PageCtrl) GetTotPages() string {
	if m != nil && m.TotPages != nil {
		return *m.TotPages
	}
	return ""
}

func (m *PBSResMultiDataMsg_PageCtrl) GetCurPage() string {
	if m != nil && m.CurPage != nil {
		return *m.CurPage
	}
	return ""
}

func (m *PBSResMultiDataMsg_PageCtrl) GetCurPageNum() string {
	if m != nil && m.CurPageNum != nil {
		return *m.CurPageNum
	}
	return ""
}

type PBSResMultiDataMsg_CertInfo struct {
	TranHash         *string `protobuf:"bytes,1,req,name=tranHash" json:"tranHash,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PBSResMultiDataMsg_CertInfo) Reset()                    { *m = PBSResMultiDataMsg_CertInfo{} }
func (m *PBSResMultiDataMsg_CertInfo) String() string            { return proto.CompactTextString(m) }
func (*PBSResMultiDataMsg_CertInfo) ProtoMessage()               {}
func (*PBSResMultiDataMsg_CertInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9, 3} }

func (m *PBSResMultiDataMsg_CertInfo) GetTranHash() string {
	if m != nil && m.TranHash != nil {
		return *m.TranHash
	}
	return ""
}

type PBSResMultiDataMsg_SignStepInfo struct {
	Step             *string `protobuf:"bytes,1,req,name=step" json:"step,omitempty"`
	MemId            *string `protobuf:"bytes,2,req,name=memId" json:"memId,omitempty"`
	Status           *string `protobuf:"bytes,3,req,name=status" json:"status,omitempty"`
	SignBlock        *string `protobuf:"bytes,4,req,name=signBlock" json:"signBlock,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PBSResMultiDataMsg_SignStepInfo) Reset()         { *m = PBSResMultiDataMsg_SignStepInfo{} }
func (m *PBSResMultiDataMsg_SignStepInfo) String() string { return proto.CompactTextString(m) }
func (*PBSResMultiDataMsg_SignStepInfo) ProtoMessage()    {}
func (*PBSResMultiDataMsg_SignStepInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{9, 4}
}

func (m *PBSResMultiDataMsg_SignStepInfo) GetStep() string {
	if m != nil && m.Step != nil {
		return *m.Step
	}
	return ""
}

func (m *PBSResMultiDataMsg_SignStepInfo) GetMemId() string {
	if m != nil && m.MemId != nil {
		return *m.MemId
	}
	return ""
}

func (m *PBSResMultiDataMsg_SignStepInfo) GetStatus() string {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return ""
}

func (m *PBSResMultiDataMsg_SignStepInfo) GetSignBlock() string {
	if m != nil && m.SignBlock != nil {
		return *m.SignBlock
	}
	return ""
}

// 手动添加订单信息，由需方传到DLS
type PBDemOrderManualMsg struct {
	OrderInfo        *PBDemOrderManualMsg_OrderInfo      `protobuf:"bytes,1,req,name=orderInfo" json:"orderInfo,omitempty"`
	OrderDtlInfo     []*PBDemOrderManualMsg_OrderDtlInfo `protobuf:"bytes,2,rep,name=orderDtlInfo" json:"orderDtlInfo,omitempty"`
	XXX_unrecognized []byte                              `json:"-"`
}

func (m *PBDemOrderManualMsg) Reset()                    { *m = PBDemOrderManualMsg{} }
func (m *PBDemOrderManualMsg) String() string            { return proto.CompactTextString(m) }
func (*PBDemOrderManualMsg) ProtoMessage()               {}
func (*PBDemOrderManualMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *PBDemOrderManualMsg) GetOrderInfo() *PBDemOrderManualMsg_OrderInfo {
	if m != nil {
		return m.OrderInfo
	}
	return nil
}

func (m *PBDemOrderManualMsg) GetOrderDtlInfo() []*PBDemOrderManualMsg_OrderDtlInfo {
	if m != nil {
		return m.OrderDtlInfo
	}
	return nil
}

type PBDemOrderManualMsg_OrderInfo struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	OrderExpiryDate  *string `protobuf:"bytes,2,req,name=orderExpiryDate" json:"orderExpiryDate,omitempty"`
	NeedCache        *string `protobuf:"bytes,3,req,name=needCache" json:"needCache,omitempty"`
	CacheTime        *string `protobuf:"bytes,4,req,name=cacheTime" json:"cacheTime,omitempty"`
	DemMemId         *string `protobuf:"bytes,5,req,name=demMemId" json:"demMemId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PBDemOrderManualMsg_OrderInfo) Reset()         { *m = PBDemOrderManualMsg_OrderInfo{} }
func (m *PBDemOrderManualMsg_OrderInfo) String() string { return proto.CompactTextString(m) }
func (*PBDemOrderManualMsg_OrderInfo) ProtoMessage()    {}
func (*PBDemOrderManualMsg_OrderInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{10, 0}
}

func (m *PBDemOrderManualMsg_OrderInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *PBDemOrderManualMsg_OrderInfo) GetOrderExpiryDate() string {
	if m != nil && m.OrderExpiryDate != nil {
		return *m.OrderExpiryDate
	}
	return ""
}

func (m *PBDemOrderManualMsg_OrderInfo) GetNeedCache() string {
	if m != nil && m.NeedCache != nil {
		return *m.NeedCache
	}
	return ""
}

func (m *PBDemOrderManualMsg_OrderInfo) GetCacheTime() string {
	if m != nil && m.CacheTime != nil {
		return *m.CacheTime
	}
	return ""
}

func (m *PBDemOrderManualMsg_OrderInfo) GetDemMemId() string {
	if m != nil && m.DemMemId != nil {
		return *m.DemMemId
	}
	return ""
}

type PBDemOrderManualMsg_OrderDtlInfo struct {
	ConnObjId        *string `protobuf:"bytes,1,req,name=connObjId" json:"connObjId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PBDemOrderManualMsg_OrderDtlInfo) Reset()         { *m = PBDemOrderManualMsg_OrderDtlInfo{} }
func (m *PBDemOrderManualMsg_OrderDtlInfo) String() string { return proto.CompactTextString(m) }
func (*PBDemOrderManualMsg_OrderDtlInfo) ProtoMessage()    {}
func (*PBDemOrderManualMsg_OrderDtlInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{10, 1}
}

func (m *PBDemOrderManualMsg_OrderDtlInfo) GetConnObjId() string {
	if m != nil && m.ConnObjId != nil {
		return *m.ConnObjId
	}
	return ""
}

// 手动添加订单，由DLS传回需方响应信息
type PBDlsOrderManualMsg struct {
	Status           *string `protobuf:"bytes,1,req,name=status" json:"status,omitempty"`
	ErrNo            *string `protobuf:"bytes,2,req,name=errNo" json:"errNo,omitempty"`
	ErrMsg           *string `protobuf:"bytes,3,req,name=errMsg" json:"errMsg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PBDlsOrderManualMsg) Reset()                    { *m = PBDlsOrderManualMsg{} }
func (m *PBDlsOrderManualMsg) String() string            { return proto.CompactTextString(m) }
func (*PBDlsOrderManualMsg) ProtoMessage()               {}
func (*PBDlsOrderManualMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *PBDlsOrderManualMsg) GetStatus() string {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return ""
}

func (m *PBDlsOrderManualMsg) GetErrNo() string {
	if m != nil && m.ErrNo != nil {
		return *m.ErrNo
	}
	return ""
}

func (m *PBDlsOrderManualMsg) GetErrMsg() string {
	if m != nil && m.ErrMsg != nil {
		return *m.ErrMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*PBDReqDataMsg)(nil), "PB_d_req_data_msg")
	proto.RegisterType((*PBDReqDataMsg_TranInfo)(nil), "PB_d_req_data_msg.TranInfo")
	proto.RegisterType((*PBDReqDataMsg_CertInfo)(nil), "PB_d_req_data_msg.CertInfo")
	proto.RegisterType((*PBDReqDataMsg_SignStepInfo)(nil), "PB_d_req_data_msg.SignStepInfo")
	proto.RegisterType((*PBDReqDataMsg_TaskType)(nil), "PB_d_req_data_msg.TaskType")
	proto.RegisterType((*PBSResDataMsg)(nil), "PB_s_res_data_msg")
	proto.RegisterType((*PBSResDataMsg_TranInfo)(nil), "PB_s_res_data_msg.TranInfo")
	proto.RegisterType((*PBSResDataMsg_DigEnv)(nil), "PB_s_res_data_msg.DigEnv")
	proto.RegisterType((*PBSResDataMsg_CertInfo)(nil), "PB_s_res_data_msg.CertInfo")
	proto.RegisterType((*PBSResDataMsg_SignStepInfo)(nil), "PB_s_res_data_msg.SignStepInfo")
	proto.RegisterType((*DReqKeyGenMsg)(nil), "d_req_keyGen_msg")
	proto.RegisterType((*DResKeyGenMsg)(nil), "d_res_keyGen_msg")
	proto.RegisterType((*PBDDlsReqMsg)(nil), "PB_d_dls_req_msg")
	proto.RegisterType((*PBDDlsResMsg)(nil), "PB_d_dls_res_msg")
	proto.RegisterType((*LmtDDlsReqMsg)(nil), "lmt_d_dls_req_msg")
	proto.RegisterType((*LmtDDlsResMsg)(nil), "lmt_d_dls_res_msg")
	proto.RegisterType((*PBDReqMultiDataMsg)(nil), "PB_d_req_multi_data_msg")
	proto.RegisterType((*PBDReqMultiDataMsg_TranInfo)(nil), "PB_d_req_multi_data_msg.TranInfo")
	proto.RegisterType((*PBDReqMultiDataMsg_CondInfo)(nil), "PB_d_req_multi_data_msg.CondInfo")
	proto.RegisterType((*PBDReqMultiDataMsg_PageCtrl)(nil), "PB_d_req_multi_data_msg.PageCtrl")
	proto.RegisterType((*PBDReqMultiDataMsg_CertInfo)(nil), "PB_d_req_multi_data_msg.CertInfo")
	proto.RegisterType((*PBDReqMultiDataMsg_SignStepInfo)(nil), "PB_d_req_multi_data_msg.SignStepInfo")
	proto.RegisterType((*PBSResMultiDataMsg)(nil), "PB_s_res_multi_data_msg")
	proto.RegisterType((*PBSResMultiDataMsg_TranInfo)(nil), "PB_s_res_multi_data_msg.TranInfo")
	proto.RegisterType((*PBSResMultiDataMsg_DigEnv)(nil), "PB_s_res_multi_data_msg.DigEnv")
	proto.RegisterType((*PBSResMultiDataMsg_PageCtrl)(nil), "PB_s_res_multi_data_msg.PageCtrl")
	proto.RegisterType((*PBSResMultiDataMsg_CertInfo)(nil), "PB_s_res_multi_data_msg.CertInfo")
	proto.RegisterType((*PBSResMultiDataMsg_SignStepInfo)(nil), "PB_s_res_multi_data_msg.SignStepInfo")
	proto.RegisterType((*PBDemOrderManualMsg)(nil), "PB_dem_order_manual_msg")
	proto.RegisterType((*PBDemOrderManualMsg_OrderInfo)(nil), "PB_dem_order_manual_msg.OrderInfo")
	proto.RegisterType((*PBDemOrderManualMsg_OrderDtlInfo)(nil), "PB_dem_order_manual_msg.OrderDtlInfo")
	proto.RegisterType((*PBDlsOrderManualMsg)(nil), "PB_dls_order_manual_msg")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 901 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0x51, 0x6f, 0xe3, 0x44,
	0x10, 0x56, 0x1b, 0xa7, 0x89, 0xa7, 0x81, 0x34, 0x11, 0xd2, 0x85, 0x1c, 0xd2, 0xf5, 0x22, 0x21,
	0x95, 0x07, 0x82, 0x68, 0x85, 0x78, 0x40, 0x42, 0xa2, 0xe9, 0x89, 0x2b, 0xe2, 0xda, 0xde, 0xa5,
	0xef, 0xd1, 0x26, 0x3b, 0xf8, 0x7c, 0xb1, 0xd7, 0xe9, 0xee, 0x1a, 0x2e, 0x8f, 0xfc, 0x06, 0x5e,
	0xf9, 0x43, 0xfc, 0x0d, 0x24, 0xfe, 0x07, 0xda, 0xf1, 0xda, 0x6b, 0xb7, 0x71, 0x02, 0x08, 0x8e,
	0xc7, 0x5d, 0x7f, 0x33, 0xf3, 0xcd, 0xcc, 0x37, 0xb3, 0x06, 0x3f, 0x56, 0xc1, 0x78, 0x25, 0x13,
	0x9d, 0x8c, 0x7e, 0x6f, 0x40, 0xef, 0xe6, 0x7c, 0xc6, 0x67, 0x12, 0xef, 0x66, 0x9c, 0x69, 0x36,
	0x8b, 0x55, 0xd0, 0xff, 0x14, 0xda, 0x5a, 0x32, 0x71, 0x29, 0x7e, 0x48, 0x06, 0x7b, 0xc7, 0xfb,
	0x27, 0x87, 0xa7, 0x8f, 0xc7, 0x0f, 0x50, 0xe3, 0x5b, 0x0b, 0x31, 0xf0, 0x05, 0x4a, 0x4d, 0xf0,
	0xfd, 0x5a, 0xf8, 0xc4, 0x42, 0xfa, 0x9f, 0x43, 0x5b, 0x85, 0x41, 0xe6, 0xbd, 0x71, 0xdc, 0x38,
	0x39, 0x3c, 0x7d, 0xb2, 0x01, 0x3e, 0x0d, 0x03, 0x31, 0xd5, 0xb8, 0xca, 0x23, 0x68, 0xa6, 0x96,
	0xb7, 0xeb, 0x15, 0x0e, 0x3c, 0x32, 0xd9, 0x48, 0xc8, 0x42, 0x86, 0x09, 0xb4, 0x0b, 0x72, 0x3d,
	0xf0, 0x25, 0xde, 0xa5, 0xa8, 0xf4, 0x25, 0xa7, 0x64, 0xfc, 0xfe, 0xfb, 0x70, 0x90, 0x2a, 0x94,
	0x97, 0x9c, 0xd8, 0xd2, 0xd9, 0x78, 0xbf, 0xe4, 0x83, 0x46, 0x7e, 0x0e, 0xb9, 0x8d, 0x65, 0xce,
	0x1d, 0xf0, 0x50, 0x87, 0x7c, 0xd0, 0xa4, 0x53, 0x1f, 0x80, 0x22, 0x4a, 0x26, 0x02, 0x1c, 0x1c,
	0x98, 0xbb, 0xe1, 0x47, 0xd0, 0x2e, 0xd2, 0x3b, 0xca, 0x8a, 0xf7, 0x9c, 0xa9, 0xd7, 0x59, 0xbc,
	0xe1, 0x15, 0x74, 0x2a, 0xd9, 0x74, 0xc0, 0x53, 0x1a, 0x57, 0x96, 0xcd, 0x7b, 0xd0, 0x8c, 0x31,
	0x2e, 0x93, 0x51, 0x9a, 0xe9, 0x54, 0x59, 0x32, 0x3d, 0xf0, 0x4d, 0xb5, 0xce, 0xa3, 0x64, 0xb1,
	0xcc, 0xf8, 0x0c, 0xc7, 0xd0, 0xce, 0x53, 0xcd, 0xb9, 0x87, 0x79, 0x6e, 0x7d, 0x80, 0x25, 0xae,
	0x5f, 0xca, 0x35, 0xf1, 0x27, 0x97, 0xa3, 0xdf, 0xb2, 0x26, 0xab, 0x99, 0x44, 0xb5, 0xb3, 0xc9,
	0x55, 0x94, 0x6b, 0xf2, 0x27, 0x70, 0xc0, 0xc3, 0xe0, 0x99, 0xf8, 0x71, 0xb0, 0x7f, 0xbc, 0x77,
	0x72, 0x78, 0xfa, 0xe1, 0x06, 0xf0, 0x05, 0x01, 0x2a, 0x7a, 0x68, 0x10, 0x78, 0x93, 0xe7, 0x8d,
	0x7a, 0xf0, 0x9c, 0x1e, 0xee, 0xc1, 0xcb, 0x15, 0x1c, 0x7e, 0x5d, 0x6a, 0x70, 0x17, 0x5a, 0x12,
	0xd5, 0x24, 0xe1, 0xe8, 0xda, 0x2b, 0x51, 0xbd, 0x50, 0x81, 0xad, 0x68, 0x0f, 0x7c, 0x1d, 0xc6,
	0x38, 0xd5, 0x2c, 0x5e, 0x65, 0x45, 0x1d, 0x7e, 0x07, 0x07, 0x96, 0x6b, 0x17, 0x5a, 0x28, 0x16,
	0x37, 0xea, 0xa7, 0xbc, 0x80, 0x47, 0xd0, 0x36, 0x31, 0xa9, 0x7d, 0x99, 0x7d, 0x17, 0x5a, 0xe6,
	0xe6, 0x7b, 0x14, 0xb6, 0x25, 0x1d, 0xf0, 0xcc, 0x85, 0xed, 0xc6, 0x3b, 0xed, 0xfd, 0xe8, 0x02,
	0x8e, 0x32, 0xd5, 0x2f, 0x71, 0xfd, 0x2d, 0x0a, 0xea, 0x64, 0xe1, 0xa5, 0xc8, 0xc0, 0xc8, 0x9b,
	0x72, 0x32, 0xbd, 0xa2, 0x0c, 0x96, 0xb8, 0x9e, 0x22, 0x5a, 0x85, 0x8f, 0x5e, 0x65, 0x5e, 0x54,
	0xd9, 0x8b, 0x0b, 0x5e, 0x70, 0x43, 0x29, 0xaf, 0xae, 0x1d, 0x37, 0x94, 0xd2, 0x54, 0xb5, 0x91,
	0x57, 0x65, 0x95, 0xce, 0x8d, 0x03, 0xcb, 0xec, 0x06, 0x8e, 0x68, 0x24, 0x79, 0xa4, 0x88, 0xe0,
	0x4e, 0x66, 0x36, 0x88, 0x4e, 0x96, 0xe5, 0xca, 0xca, 0x24, 0xb2, 0x73, 0x37, 0xfa, 0xa6, 0xe2,
	0x51, 0x6d, 0x63, 0x99, 0x6c, 0x66, 0x39, 0x3a, 0x83, 0x5e, 0x14, 0xeb, 0xed, 0xac, 0xba, 0xd0,
	0x4a, 0x15, 0xf2, 0x73, 0x16, 0xd9, 0x79, 0x39, 0xaf, 0x1a, 0xfd, 0xa3, 0xc0, 0x7f, 0x78, 0xf0,
	0xa8, 0xd8, 0x50, 0x71, 0x1a, 0xe9, 0xd0, 0x4d, 0xde, 0xd9, 0x83, 0xc9, 0x7b, 0x3a, 0xae, 0xc1,
	0xba, 0xf9, 0x3b, 0x83, 0xf6, 0x22, 0x11, 0xbc, 0xb4, 0x64, 0xeb, 0x8d, 0x26, 0x16, 0x68, 0x8c,
	0x56, 0x2c, 0xc0, 0x89, 0x96, 0x11, 0xf1, 0xda, 0x66, 0x74, 0x63, 0x81, 0x14, 0x29, 0x1f, 0x5f,
	0x6f, 0x57, 0xa4, 0x5c, 0xf9, 0x5f, 0x96, 0x86, 0xb8, 0x49, 0x43, 0xfc, 0x71, 0xad, 0x51, 0x65,
	0x94, 0x7f, 0xde, 0xfb, 0x2f, 0x97, 0x75, 0x0f, 0x7c, 0x13, 0xf6, 0x95, 0xdb, 0xd5, 0xd5, 0x75,
	0xd0, 0xca, 0x17, 0x6a, 0x51, 0xb2, 0x1e, 0xf8, 0x73, 0x0c, 0x42, 0x71, 0x1b, 0xc6, 0xe8, 0x04,
	0x82, 0x82, 0xd3, 0x05, 0x71, 0x18, 0x3e, 0x86, 0x76, 0x51, 0x2d, 0x5a, 0x3f, 0x77, 0xe6, 0x68,
	0x27, 0xfe, 0xdd, 0xee, 0x83, 0x5f, 0x9a, 0xa4, 0x33, 0xab, 0xd3, 0xbf, 0xa4, 0xb3, 0x4d, 0x58,
	0xa7, 0xb3, 0xcf, 0xee, 0xed, 0xf9, 0x27, 0xb5, 0x26, 0x76, 0x83, 0x56, 0x35, 0xb6, 0xb7, 0x35,
	0x4a, 0x8d, 0xc6, 0xb6, 0x1b, 0xed, 0xd2, 0xd8, 0x46, 0xa3, 0x8a, 0xc6, 0xe6, 0x25, 0x89, 0x7d,
	0x00, 0x9d, 0x79, 0xaa, 0xc2, 0x29, 0xca, 0x90, 0x45, 0x57, 0x89, 0x2d, 0xbc, 0x51, 0xcd, 0xdb,
	0x90, 0xbb, 0x8d, 0x9f, 0x3f, 0x29, 0x8d, 0x7b, 0x4f, 0x8a, 0xf7, 0x50, 0x43, 0xcd, 0x7f, 0xfd,
	0x49, 0x79, 0x59, 0xd2, 0x97, 0xd1, 0x7b, 0xa2, 0xaf, 0xd2, 0xd8, 0x39, 0xd3, 0x89, 0x36, 0x9f,
	0x95, 0x73, 0xb6, 0x48, 0x25, 0x29, 0xb0, 0x91, 0xff, 0x03, 0xd8, 0x0b, 0x63, 0xf6, 0x7f, 0xbc,
	0x52, 0xbf, 0xee, 0x67, 0xdb, 0x0f, 0xe3, 0x59, 0x22, 0x39, 0xca, 0x59, 0xcc, 0x44, 0xca, 0x22,
	0x52, 0xe5, 0x17, 0xe0, 0xd3, 0x5d, 0x49, 0x96, 0xa3, 0x71, 0x0d, 0x78, 0x7c, 0x9d, 0x23, 0xfb,
	0x5f, 0x41, 0x87, 0xbe, 0x5e, 0xe8, 0xc8, 0xee, 0x40, 0xb7, 0x64, 0x6a, 0x2d, 0x2d, 0x78, 0xf8,
	0x06, 0x7c, 0xe7, 0xa9, 0x03, 0x9e, 0x60, 0xc5, 0x70, 0x3f, 0x82, 0x2e, 0xd9, 0x3e, 0x7b, 0xbb,
	0x0a, 0xe5, 0xfa, 0x82, 0x69, 0x74, 0xbf, 0x0d, 0x02, 0x91, 0x4f, 0xd8, 0xe2, 0x35, 0xba, 0x4c,
	0x17, 0xe6, 0x48, 0xab, 0xc0, 0x2b, 0x7a, 0x8b, 0xf1, 0x0b, 0x2a, 0x4f, 0x26, 0x84, 0xa7, 0xd0,
	0x29, 0xc7, 0x26, 0xa3, 0x44, 0x88, 0xeb, 0xf9, 0x9b, 0x7c, 0xa7, 0x8d, 0x9e, 0x67, 0xd5, 0x89,
	0xd4, 0xc3, 0xea, 0xfc, 0xbd, 0x67, 0xe6, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfd, 0x41, 0x8d,
	0xca, 0xcb, 0x0b, 0x00, 0x00,
}
